import re

def main(inn,out):
    route_parts = inn.ta_info['idroute'].split('_')
    if len(route_parts) < 2:
        raise Exception("Route name not properly formatted")
    marketplace = route_parts[1]
    if not re.search(r"^[A-Z]{2}$", marketplace):
        raise Exception("Marketplace must be 2 capital letters")
    out.put({'BOTSID':'ROOT'},{'BOTSID':'HEADERS','interchangeSenderName':inn.ta_info['frompartner']})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'HEADERS','interchangeRecipientName':inn.ta_info['topartner']})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'HEADERS','uniqueMessageReference':inn.get({'BOTSID':'UNH','0062':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'HEADERS','messageTypeIdentifier':inn.get({'BOTSID':'UNH','S009.0065':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'HEADERS','messageTypeVersionNumber':inn.get({'BOTSID':'UNH','S009.0052':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'HEADERS','messageTypeControllingAgency':inn.get({'BOTSID':'UNH','S009.0051':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'HEADERS','associationAssignedCode':inn.get({'BOTSID':'UNH','S009.0057':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','marketplace': marketplace})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','orderNumber':inn.get({'BOTSID':'UNH'},{'BOTSID':'BGM','C002.1001':'220','1004':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','dateIssued':inn.get({'BOTSID':'UNH'},{'BOTSID':'DTM','C507.2005':'137','C507.2380':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','deliveryDateStart':inn.get({'BOTSID':'UNH'},{'BOTSID':'DTM','C507.2005':'64','C507.2380':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','deliveryDateEnd':inn.get({'BOTSID':'UNH'},{'BOTSID':'DTM','C507.2005':'63','C507.2380':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','firstOrderStatus':inn.get({'BOTSID':'UNH'},{'BOTSID':'RFF','C506.1153':'ADE','C506.1154':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','promotionDealNumber':inn.get({'BOTSID':'UNH'},{'BOTSID':'RFF','C506.1153':'PD','C506.1154':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','amazonVendorCode':inn.get({'BOTSID':'UNH'},{'BOTSID':'RFF','C506.1153':'CR','C506.1154':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','buyerGLN':inn.get({'BOTSID':'UNH'},{'BOTSID':'NAD','3035':'BY','C082.3039':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','supplierGLN':inn.get({'BOTSID':'UNH'},{'BOTSID':'NAD','3035':'SU','C082.3039':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','shipToGLN':inn.get({'BOTSID':'UNH'},{'BOTSID':'NAD','3035':'DP','C082.3039':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','shipToCountryCode':inn.get({'BOTSID':'UNH'},{'BOTSID':'NAD','3035':'DP','3207':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','invoiceeGLN':inn.get({'BOTSID':'UNH'},{'BOTSID':'NAD','3035':'IV','C082.3039':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','invoiceeName1':inn.get({'BOTSID':'UNH'},{'BOTSID':'NAD','3035':'IV','C080.3036#1':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','invoiceeName2':inn.get({'BOTSID':'UNH'},{'BOTSID':'NAD','3035':'IV','C080.3036#2':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','invoiceeAddress1':inn.get({'BOTSID':'UNH'},{'BOTSID':'NAD','3035':'IV','C059.3042#1':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','invoiceeAddress2':inn.get({'BOTSID':'UNH'},{'BOTSID':'NAD','3035':'IV','C059.3042#2':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','invoiceeCity':inn.get({'BOTSID':'UNH'},{'BOTSID':'NAD','3035':'IV','3164':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','invoiceeState':inn.get({'BOTSID':'UNH'},{'BOTSID':'NAD','3035':'IV','3229':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','invoiceePostcode':inn.get({'BOTSID':'UNH'},{'BOTSID':'NAD','3035':'IV','3251':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','invoiceeCountry':inn.get({'BOTSID':'UNH'},{'BOTSID':'NAD','3035':'IV','3207':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','VATNumber':inn.get({'BOTSID':'UNH'},{'BOTSID':'NAD'},{'BOTSID':'RFF','C506.1153':'VA','C506.1154':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','currencyISOCode':inn.get({'BOTSID':'UNH'},{'BOTSID':'CUX','C504#1.6347':'2','C504#1.6343':'9','C504#1.6345':None})})
    for lin in inn.getloop({'BOTSID':'UNH'},{'BOTSID':'LIN'}):
        lout = out.putloop({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES'},{'BOTSID':'lineItems'})
        lout.put({'BOTSID':'lineItems','lineItemNumber':lin.get({'BOTSID':'LIN','1082':None})})
        lout.put({'BOTSID':'lineItems','itemNumber':lin.get({'BOTSID':'LIN','C212.7140':None})})
        lout.put({'BOTSID':'lineItems','itemNumberType':lin.get({'BOTSID':'LIN','C212.7143':None})})
        lout.put({'BOTSID':'lineItems','additionalProductId':lin.get({'BOTSID':'LIN'},{'BOTSID':'PIA','4347':'5','C212#1.7140':None})})
        lout.put({'BOTSID':'lineItems','additionalProductIdType':lin.get({'BOTSID':'LIN'},{'BOTSID':'PIA','4347':'5','C212#1.7143':None})})
        lout.put({'BOTSID':'lineItems','orderedQuantity':lin.get({'BOTSID':'LIN'},{'BOTSID':'QTY','C186.6063':'21','C186.6060':None})})
        lout.put({'BOTSID':'lineItems','netPrice':lin.get({'BOTSID':'LIN'},{'BOTSID':'PRI','C509.5125':'AAA','C509.5118':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'MESSAGES','totalLineItemsControl':inn.get({'BOTSID':'UNH'},{'BOTSID':'CNT','C270.6069':'2','C270.6066':None})})
    out.put({'BOTSID':'ROOT'},{'BOTSID':'HEADERS','numberOfMessageSegments':inn.get({'BOTSID':'UNH'},{'BOTSID':'UNT','0074':None})})
